apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: spinnaker
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spinnaker
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      imagePullSecrets:
      - name: us-west-2-ecr-registry
      containers:
      - name: primary
        image: 054159436666.dkr.ecr.us-west-2.amazonaws.com/project2/spinkubv2demo:5
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: spinnaker
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
